service: spotify-now-playing
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  logRetentionInDays: 30

functions:
  app:
    handler: src/index.handler
    timeout: 30
    environment:
      SPOTIFY_CLIENT_ID: ${env:SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${env:SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REFRESH_TOKEN: ${env:SPOTIFY_REFRESH_TOKEN}
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/recently-played
          method: get
          cors: true

package:
  patterns:
    - '!.git/**'
    - '!.env'
    - '!public/**'
    - 'src/**'
